name: CI Pipeline
on: 
    schedule:
        - cron: '0/1 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: printing a message
              run: echo "Hello, World!"
          